awesome_answers/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/"=>"home#index",as: :home
  get "/contact" =>"home#contact"
  post "/contact_submit"=>"home#contact_submit"
end

awesome_answers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def contact

  end

  def contact_submit
    
  end

end

awesome_answers/app/helpers/home_helper.rb
module HomeHelper
end

awesome_answers/app/views/home/contact.html.erb
<h2>contact us</h2>
<%= form_tag contact_submit_path do%>
    <div>
      <%= label_tag :full_name %>

      <%= text_field_tag :full_name %>
    </div>
    <div>
      <%= label_tag :email %>

      <%= text_field_tag :email %>
    </div>
    <div>
      <%= label_tag :message %>

      <%= text_field_tag :message %>
    </div>
    <%= submit_tag "Contact US" %>

<% end %>

awesome_answers/app/views/home/contact_submit.html.erb
asdasdasdasd

awesome_answers/app/views/home/index.html.erb
<h2>index</h2>

awesome_answers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= link_to "Home",home_path%>
  <%= link_to "Contact us",contact_path %>
  <hr>
    <%= yield %>
  </body>
</html>