amazon/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'questions/index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/"=>"welcome#home",as: :home
  get "/about"=>"welcome#about"
  get "/contact"=>"welcome#contact"
  post "/contact_submit"=>"welcome#contact_submit"
  get "/admin/questions/index"=>"admin/questions#index"
  get


end

amazon/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def index
  end
end

amazon/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home

  end

  def about

  end

  def contact

  end
  def contact_submit
    @name=params[:name]
  end




end

amazon/app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

amazon/app/helpers/welcome_helper.rb
module WelcomeHelper
end

amazon/app/views/admin/questions/index.html.erb
<h1>Admin::Questions#index</h1>
<p>Find me in app/views/admin/questions/index.html.erb</p>

amazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= link_to "home",home_path  %>
<%= link_to "about",about_path  %>
<%= link_to "contact",contact_path  %>
    <%= yield %>
  </body>
</html>

amazon/app/views/welcome/about.html.erb
<h1>about</h1>

amazon/app/views/welcome/contact.html.erb
<h2>contact</h2>
<%= form_tag("/contact_submit") do %>
    <div>
      <%= label_tag 'name' %>
      <%= text_field_tag 'name' %>
    </div>
    <div>
      <%= label_tag 'email' %>
      <%= email_field_tag 'email' %>
    </div>
    <div>
      <%= label_tag 'message' %>
      <%= text_area_tag 'message' %>
    </div>


    <%= submit_tag "Submit"%>


<% end %>

amazon/app/views/welcome/contact_submit.html.erb
<h2>Contact submit</h2>

<p>Hi,<%= @name %></p>

amazon/app/views/welcome/home.html.erb
<h1>home</h1>